const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.OnDestroyed
	];
};
self.C3_JsPropNameTable = [
	{Mosaico: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Piscar: 0},
	{samurai: 0},
	{personagemSensor: 0},
	{Sprite: 0},
	{Sólido: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Teclado: 0},
	{Sprite8: 0},
	{FonteDeSprites: 0},
	{DIRECAO: 0},
	{Sprite9: 0},
	{sensor_porco: 0},
	{sensor_porco2: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{Girar: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{ChatGPTImage19_04_202620_48_: 0},
	{Texto: 0},
	{ChatGPTImage19_04_202620_51_: 0},
	{ChatGPTImage19_04_202620_53_: 0},
	{Mouse: 0},
	{ChatGPTImage19_04_202620_55_: 0},
	{Sprite19: 0},
	{Botão: 0},
	{Botão2: 0},
	{Variável1: 0}
];

self.InstanceType = {
	Mosaico: class extends self.ITilemapInstance {},
	samurai: class extends self.ISpriteInstance {},
	personagemSensor: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	sensor_porco: class extends self.ISpriteInstance {},
	sensor_porco2: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	ChatGPTImage19_04_202620_48_: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	ChatGPTImage19_04_202620_51_: class extends self.ISpriteInstance {},
	ChatGPTImage19_04_202620_53_: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	ChatGPTImage19_04_202620_55_: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Botão2: class extends self.IButtonInstance {}
}